name: Deploy backend to Docker Hub and Kubernetes

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "backend-deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_HASH: ${{ steps.vars.outputs.COMMIT_HASH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Git commit hash
        id: vars
        run: echo "COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.vars.outputs.COMMIT_HASH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_BASE64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set Kubeconfig context
        run: |
          kubectl config use-context <kubernetes-cluster>

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/backend \
            backend=docker.io/${{ secrets.DOCKER_USERNAME }}/backend:${{ needs.build.outputs.COMMIT_HASH }} \
            -n project

      - name: Verify Deployment Rollout
        run: |
          kubectl rollout status deployment/backend -n project
